Models/Session.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cinema.Models
{
    public class Session
    {
        [Key]
        [Display(Name = "Сеанс")]
        public int session_id { get; set; }

        [Required(ErrorMessage = "Введите фильм")]
        [Display(Name = "Фильм")]
        public int fk_film { get; set; }

        [Required(ErrorMessage = "Введите зал")]
        [Display(Name = "Зал")]
        public int fk_hall { get; set; }

        [BindProperty, DataType(DataType.Date)]
        [Column(TypeName = "date")]
        [Required(ErrorMessage = "Введите дату сеанса")]
        [Display(Name = "Дата сеанса")]
        public DateTime session_date { get; set; }

        [BindProperty, DataType(DataType.Time)]
        [Column(TypeName = "interval")]
        [Required(ErrorMessage = "Введите время начала")]
        [Display(Name = "Время начала")]
        public TimeSpan start_time { get; set; }

        [BindProperty, DataType(DataType.Time)]
        [Column(TypeName = "interval")]
        [Required(ErrorMessage = "Введите время окончания")]
        [Display(Name = "Время окончания")]
        public TimeSpan end_time { get; set; }
    }
}

Controllers/SessionController.cs
using Cinema.Context;
using Cinema.Interfaces;
using Cinema.Models.ViewModels;
using Cinema.Models;
using Cinema.Service.Implementations;
using Cinema.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.Design;
using System.IO;
using static System.Net.WebRequestMethods;

namespace Cinema.Controllers
{
    public class SessionController : Controller
    {
        private readonly ISessionService sessionService;
        private readonly IFilmService filmService;
        private readonly IHallService hallService;
        private readonly ISessionRowPlaceService sessionRowPlaceService;
        public SessionController(ISessionService sessionService, IFilmService filmService, IHallService hallService, ISessionRowPlaceService sessionRowPlaceService)
        {
            this.sessionService = sessionService;
            this.hallService = hallService;
            this.filmService = filmService;
            this.sessionRowPlaceService = sessionRowPlaceService;
        }

        [HttpGet]
        public async Task<IActionResult> GetSessions()
        {
            var sessions = await sessionService.GetSessions();
            if (sessions.StatusCode == Enum.StatusCode.OK)
            {
                return View(sessions.Data.ToList());
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> GetSession(int id)
        {
            var sessions = await sessionService.GetSession(id);
            if (sessions.StatusCode == Enum.StatusCode.OK)
            {
                return View(sessions.Data);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> CreateSession()

        {
            var halls = await hallService.GetHalls();
            if (halls.StatusCode == Enum.StatusCode.HallNotFound)
            {
                return View("Index");
            }
            ViewBag.Halls = new SelectList(halls.Data, "hall_id", "screen_type");

            var films = await filmService.GetFilms();
            if (films.StatusCode == Enum.StatusCode.FilmNotFound)
            {
                return View("Index");
            }
            var Films = films.Data.Select(x => new
            {
                film_id = x.film_id,
                req_info = x.film_name + " | " + x.release_date.ToShortDateString()
            });
            ViewBag.Films = new SelectList(Films, "film_id", "req_info");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateSession(Session session)
        {
            if (ModelState.IsValid)
            {
                if (session.session_id == 0)
                {
                    await sessionService.CreateSession(session);

                    var sessions = await sessionService.GetSessions();

                    var hall = await hallService.GetHall(sessions.Data.ToList().Last().fk_hall);

                    SessionRowPlace srp = new SessionRowPlace();
                    for (int indexRow = 0; indexRow < hall.Data.count_of_rows; indexRow++)
                    {
                        for(int indexPlace = 0; indexPlace < hall.Data.places_per_row; indexPlace++)
                        {
                            srp.fk_session = sessions.Data.ToList().Last().session_id;
                            srp.row_ = indexRow + 1;
                            srp.place_ = indexPlace + 1;
                            srp.status = "Available";

                            await sessionRowPlaceService.CreateSessionRowPlace(srp);
                        }
                    }
                }
                else
                {
                    await sessionService.Edit(session);
                }
            }

            return RedirectToAction("Index", "Database");
        }

        [HttpGet]
        public async Task<IActionResult> DeleteSession()
        {
            var temp_sessions = await sessionService.GetSessions();
            if(temp_sessions.StatusCode == Enum.StatusCode.OK)
            {
                var sessions = temp_sessions.Data.ToList();
                if (sessions.Count != 0)
                {
                    var Sessions = sessions.Select(x => new
                    {
                        session_id = x.session_id,
                        req_info = x.session_date + " | " + x.start_time + " - " + x.end_time + " | " + x.fk_hall
                    });
                    ViewBag.Sessions = new SelectList(Sessions, "session_id", "req_info");

                    return View();
                }
            }


            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteSession(Session session)
        {
            var sessions = await sessionService.DeleteSession(session);
            if (sessions.StatusCode == Enum.StatusCode.OK)
            {
                return RedirectToAction("Index", "Database");
            }

            return RedirectToAction("Index");
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Session/CreateSession.cshtml
@model Cinema.Models.ViewModels.SessionFilmHallViewModel
@{
    ViewData["Title"] = "Добавление сеанса";
}

<div class="form-container">
    <form method="post" class="form" asp-controller="Session" asp-action="CreateSession">
        <label class="form-label" asp-for="@Model.film.film_id"></label>
        <select class ="form-select" asp-for=@Model.session.fk_film asp-items="ViewBag.Films"></select>
        <span class="form-span" asp-validation-for="@Model.film.film_id"></span>

        <label class="form-label" asp-for="@Model.hall.hall_id"></label>
        <select class="form-select" asp-for=@Model.session.fk_hall asp-items="ViewBag.Halls"></select>
        <span class="form-span" asp-validation-for="@Model.hall.hall_id"></span>

        <label class="form-label" asp-for="@Model.session.session_date"></label>
        <input class="form-input" asp-for="@Model.session.session_date" />
        <span class="form-span" asp-validation-for="@Model.session.session_date"></span>

        <label class="form-label" asp-for="@Model.session.start_time"></label>
        <input class="form-input" asp-for="@Model.session.start_time" />
        <span class="form-span" asp-validation-for="@Model.session.start_time"></span>

        <input class ="form-button" type="submit" value="Добавить сеанс" />
    </form>
</div>

Views/Session/DeleteSession.cshtml
@model Session
@{
    ViewData["Title"] = "Удаление сеанса";
}

<div class="form-container">
    <form method="post" class="form" asp-controller="Session" asp-action="DeleteSession">
        <label class="form-label" asp-for="@Model.session_id"></label>
        <select class="form-select" asp-for=@Model.session_id asp-items="ViewBag.Sessions"></select>
        <span class="form-span" asp-validation-for="@Model.session_id"></span>

        <input class="form-button" type="submit" value="Удалить сеанс" />
    </form>
</div>

Views/Session/GetSession.cshtml
@model Session
@{
    Layout = "_Layout";
}

Views/Session/GetSessions.cshtml
@model List<Session>

@{

}

@foreach (var session in Model)
{
    <p>@session.session_date</p>
}

Views/Session/Index.cshtml
@{

}

<div class="button-main-edit">
    <a href="/Session/CreateSession" class="button-main">Добавить сеанс</a>
    <a href="/Session/DeleteSession" class="button-main">Удалить сеанс</a>
</div>