Models/Film.cs
using Cinema.Enum;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using Npgsql.Internal.TypeHandlers.DateTimeHandlers;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.SqlTypes;

namespace Cinema.Models
{
    public class Film
    {
        [Key]
        [Display(Name = "Фильм")]
        public int film_id { get; set; }

        [Column(TypeName = "varchar(150)")]
        [Display(Name = "Название фильма")]
        [MaxLength(150, ErrorMessage = "Максимальное кол-во символов - 150")]
        [Required(ErrorMessage = "Введите название фильма")]
        public string film_name { get; set; } = string.Empty;

        [Column(TypeName = "varchar(1000)")]
        [Display(Name = "Описание")]
        [MaxLength(150, ErrorMessage = "Максимальное кол-во символов - 1000")]
        [Required(ErrorMessage = "Введите описание")]
        public string description { get; set; } = string.Empty;

        [BindProperty, DataType(DataType.Date)]
        [Column(TypeName = "date")]
        [Display(Name = "Дата выхода")]
        [Required(ErrorMessage = "Введите дату выхода")]
        public DateTime release_date { get; set; }

        [BindProperty, DataType(DataType.Time)]
        [Column(TypeName = "interval")]
        [Display(Name = "Длительность")]
        [Required(ErrorMessage = "Введите длительность")]
        public TimeSpan duration { get; set; }

        [Column(TypeName = "real")]
        [Display(Name = "Оценка")]
        [Required(ErrorMessage = "Введите оценку")]
        public float rating { get; set; }

        [Column(TypeName = "money")]
        [Display(Name = "Бюджет")]
        [Required(ErrorMessage = "Введите бюджет")]
        public double budget { get; set; }

        [Display(Name = "Постер")]
        [Required(ErrorMessage = "Выберите изображение")]
        public string poster { get; set; } = string.Empty;

        [Display(Name = "Режисер")]
        [Required(ErrorMessage = "Введите режисера")]
        public int fk_director { get; set; }

        [Display(Name = "Возрастное ограничение")]
        [Required(ErrorMessage = "Введите возрастное ограничение")]
        public int fk_restriction { get; set; }
    }
}

Controllers/FilmController.cs
using Cinema.Interfaces;
using Cinema.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Cinema.Enum;
using Microsoft.AspNetCore.Authorization;
using Cinema.Models.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Cinema.Models;
using System.Diagnostics.Metrics;
using Cinema.Context;
using System;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.IdentityModel.Tokens;

namespace Cinema.Controllers
{
    public class FilmController : Controller
    {
        private readonly IFilmService filmService;
        private readonly IGenreService genreService;
        private readonly IOriginCountryService originCountryService;
        private readonly IDirectorService directorService;
        private readonly IRestrictionService restrictionService;
        private readonly IFilmGenreService filmGenreService;
        private readonly IFilmCountryService filmCountryService;
        public FilmController(IFilmService filmService, IGenreService genreService, IOriginCountryService originCountryService, IDirectorService directorService, 
            IRestrictionService restrictionService, IFilmGenreService filmGenreService, IFilmCountryService filmCountryService)
        {
            this.filmService = filmService;
            this.originCountryService = originCountryService;
            this.genreService = genreService;
            this.directorService = directorService;
            this.restrictionService = restrictionService;
            this.filmCountryService = filmCountryService;
            this.filmGenreService = filmGenreService;
        }

        [HttpGet]
        public async Task<IActionResult> GetFilms()
        {
            var films = await filmService.GetFilms();
            if(films.StatusCode == Enum.StatusCode.OK)
            {
                return View(films.Data.ToList());
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> GetFilm(int id)
        {
            var films = await filmService.GetFilm(id);
            if (films.StatusCode == Enum.StatusCode.OK)
            {
                return View(films.Data);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> CreateFilm()
        
        {
            var genres = await genreService.GetGenres();
            List<GenreCheckBoxViewModel> genreCheckBox = new List<GenreCheckBoxViewModel>();
            foreach (var elem in genres.Data)
            {
                GenreCheckBoxViewModel genreCheckBoxElem = new GenreCheckBoxViewModel();
                genreCheckBoxElem.Id = elem.genre_id;
                genreCheckBoxElem.Name = elem.genre_name;
                genreCheckBoxElem.IsChecked = false;
                genreCheckBox.Add(genreCheckBoxElem);
            }

            var countries = await originCountryService.GetOriginCountries();
            List<CountryCheckBoxViewModel> countryCheckBox = new List<CountryCheckBoxViewModel>();
            foreach (var elem in countries.Data)
            {
                CountryCheckBoxViewModel countryCheckBoxElem = new CountryCheckBoxViewModel();
                countryCheckBoxElem.Id = elem.country_id;
                countryCheckBoxElem.Name = elem.country_name;
                countryCheckBoxElem.IsChecked = false;
                countryCheckBox.Add(countryCheckBoxElem);
            }

            var directors = await directorService.GetDirectors();
            var Directors = directors.Data.Select(x => new
            {
                director_id = x.director_id,
                req_info = x.director_firstname + " " + x.director_lastname
            });
            ViewBag.Directors = new SelectList(Directors, "director_id", "req_info");

            var restrictions = await restrictionService.GetRestrictions();
            ViewBag.Restrictions = new SelectList(restrictions.Data, "restriction_id", "restriction");

            FilmGenreCountryDirectorRestrictionCheckBoxViewModel model = new FilmGenreCountryDirectorRestrictionCheckBoxViewModel();
            model.genreCheckBoxViewModel = genreCheckBox;
            model.countryCheckBoxViewModel = countryCheckBox;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateFilm(Film film, List<GenreCheckBoxViewModel> genreCheckBoxViewModel, List<CountryCheckBoxViewModel> countryCheckBoxViewModel)
        {
            if (ModelState.IsValid)
            {
                if (film.film_id == 0)
                {
                    await filmService.CreateFilm(film);

                    var films = await filmService.GetFilms();
                    var film_id = films.Data.OrderBy(x => x.film_id).ToList().Last().film_id;

                    foreach (var elem in genreCheckBoxViewModel)
                    {
                        if(elem.IsChecked == true)
                        {
                            FilmGenre fg = new FilmGenre();
                            fg.fk_genre = elem.Id;
                            fg.fk_film = film_id;
                            await filmGenreService.CreateFilmGenre(fg);
                        }
                    }
                    foreach (var elem in countryCheckBoxViewModel)
                    {
                        if (elem.IsChecked == true)
                        {
                            FilmCountry fc = new FilmCountry();
                            fc.fk_country = elem.Id;
                            fc.fk_film = film_id;
                            await filmCountryService.CreateFilmCountry(fc);
                        }
                    }
                }
            }

            return RedirectToAction("Index", "Database");
        }

        [HttpGet]
        public async Task<IActionResult> DeleteFilm()
        {
            var temp_films = await filmService.GetFilms();
            if(temp_films.StatusCode == Enum.StatusCode.OK)
            {
                var films = temp_films.Data.ToList();
                if (films.Count != 0)
                {
                    var Films = films.Select(x => new
                    {
                        film_id = x.film_id,
                        req_info = x.film_name + " | " + x.release_date.ToShortDateString()
                    });
                    ViewBag.Films = new SelectList(Films, "film_id", "req_info");

                    return View();
                }
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteFilm(Film film)
        {
            var films = await filmService.DeleteFilm(film);
            if (films.StatusCode == Enum.StatusCode.OK)
            {
                return RedirectToAction("Index", "Database");
            }

            return RedirectToAction("Index");
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Film/CreateFilm.cshtml
@model Cinema.Models.ViewModels.FilmGenreCountryDirectorRestrictionCheckBoxViewModel
@{
    ViewData["Title"] = "Добавление фильма";
}

<div class="form-container">
    <form method="post" class="form" asp-controller="Film" asp-action="CreateFilm">
        <label class="form-label" asp-for="@Model.film.film_name"></label>
        <input class="form-input" asp-for="@Model.film.film_name" />
        <span class="form-span" asp-validation-for="@Model.film.film_name"></span>

        <label class="form-label" asp-for="@Model.film.description"></label>
        <input class="form-input" asp-for="@Model.film.description" />
        <span class="form-span" asp-validation-for="@Model.film.description"></span>

        <label class="form-label" asp-for="@Model.film.release_date"></label>
        <input class="form-input" asp-for="@Model.film.release_date" />
        <span class="form-span" asp-validation-for="@Model.film.release_date"></span>

        <label class="form-label" asp-for="@Model.film.duration"></label>
        <input class="form-input" asp-for="@Model.film.duration" />
        <span class="form-span" asp-validation-for="@Model.film.duration"></span>

        <label class="form-label" asp-for="@Model.film.rating"></label>
        <input class="form-input" asp-for="@Model.film.rating" />
        <span class="form-span" asp-validation-for="@Model.film.rating"></span>

        <label class="form-label" asp-for="@Model.film.budget"></label>
        <input class="form-input" asp-for="@Model.film.budget" />
        <span class="form-span" asp-validation-for="@Model.film.budget"></span>

        <label class="form-label" asp-for="@Model.film.poster"></label>
        <input class="form-input" asp-for="@Model.film.poster" />
        <span class="form-span" asp-validation-for="@Model.film.poster"></span>

        <label class="form-label" asp-for="@Model.restriction.restriction_id"></label>
        <select class="form-select" asp-for=@Model.film.fk_restriction asp-items="ViewBag.Restrictions"></select>
        <span class="form-span" asp-validation-for="@Model.restriction.restriction_id"></span>

        <label class="form-label" asp-for="@Model.genre.genre_id"></label>
        @for (int index = 0; index < Model.genreCheckBoxViewModel.Count(); index++)
        {
            <div class="form-checkbox-container">
                <input class="form-checkbox-input" type="checkbox" asp-for="@Model.genreCheckBoxViewModel[index].IsChecked"/>
                <label class="form-checkbox-label" asp-for="@Model.genreCheckBoxViewModel[index].IsChecked">@Model.genreCheckBoxViewModel[index].Name</label>
                <input class="form-checkbox-input"  type="hidden" asp-for="@Model.genreCheckBoxViewModel[index].Id" />
                <input class="form-checkbox-input" type="hidden" asp-for="@Model.genreCheckBoxViewModel[index].Name"/>
            </div>
        }
        <span class="form-span" asp-validation-for="@Model.genre.genre_id"></span>

        <label class="form-label" asp-for="@Model.country.country_id"></label>
        @for (int index = 0; index < Model.countryCheckBoxViewModel.Count(); index++)
        {
            <div class="form-checkbox-container">
                <input class="form-checkbox-input" type="checkbox" asp-for="@Model.countryCheckBoxViewModel[index].IsChecked" />
                <label class="form-checkbox-label" asp-for="@Model.countryCheckBoxViewModel[index].IsChecked">@Model.countryCheckBoxViewModel[index].Name</label>
                <input class="form-checkbox-input" type="hidden" asp-for="@Model.countryCheckBoxViewModel[index].Id" />
                <input class="form-checkbox-input" type="hidden" asp-for="@Model.countryCheckBoxViewModel[index].Name" />
            </div>
        }
        <span class="form-span" asp-validation-for="@Model.country.country_id"></span>

        <label class="form-label" asp-for="@Model.director.director_id"></label>
        <select class="form-select" asp-for=@Model.film.fk_director asp-items="ViewBag.Directors"></select>
        <span class="form-span" asp-validation-for="@Model.director.director_id"></span>

        <input class="form-button" type="submit" value="Добавить фильм" />
    </form>
</div>

Views/Film/DeleteFilm.cshtml
@model Film
@{
    ViewData["Title"] = "Удаление фильма";
}

<div class="form-container">
    <form method="post" class="form" asp-controller="Film" asp-action="DeleteFilm">
        <label class="form-label" asp-for="@Model.film_id"></label>
        <select class="form-select" asp-for=@Model.film_id asp-items="ViewBag.Films"></select>
        <span class="form-span" asp-validation-for="@Model.film_id"></span>

        <input class="form-button" type="submit" value="Удалить фильм" />
    </form>
</div>

Views/Film/GetFilm.cshtml
@model Film
@{
    Layout = "_Layout";
}

Views/Film/GetFilms.cshtml
@model List<Film>

@{

}

@foreach (var film in Model){
    <p>@film.film_name</p>
}

Views/Film/Index.cshtml
@{

}

<div class="button-main-edit">
    <a href="/Film/CreateFilm" class="button-main">Добавить фильм</a>
    <a href="/Film/DeleteFilm" class="button-main">Удалить фильм</a>
</div>