Models/Director.cs
using Microsoft.Identity.Client;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cinema.Models
{
    public class Director
    {
        [Key]
        [Display(Name = "Режиссер")]
        public int director_id { get; set; }

        [Column(TypeName = "varchar(50)")]
        [Display(Name = "Имя режиссера")]
        [MaxLength(20, ErrorMessage = "Максимальное кол-во символов - 50")]
        [Required]
        public string director_firstname { get; set; } = string.Empty;

        [Column(TypeName = "varchar(50)")]
        [Display(Name = "Фамилия режиссера")]
        [MaxLength(20, ErrorMessage = "Максимальное кол-во символов - 50")]
        [Required]
        public string director_lastname { get; set; } = string.Empty;
    }
}

Controllers/DirectorController.cs
using Cinema.Context;
using Cinema.Models;
using Cinema.Service.Implementations;
using Cinema.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Identity.Client;

namespace Cinema.Controllers
{
    public class DirectorController : Controller
    {
        private readonly IDirectorService directorService;
        public DirectorController(IDirectorService directorService)
        {
            this.directorService = directorService;
        }

        [HttpGet]
        public async Task<IActionResult> GetDirectors()
        {
            var directors = await directorService.GetDirectors();
            if (directors.StatusCode == Enum.StatusCode.OK)
            {
                return View(directors.Data.ToList());
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> GetDirector(int id)
        {
            var directors = await directorService.GetDirector(id);
            if (directors.StatusCode == Enum.StatusCode.OK)
            {
                return View(directors.Data);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult CreateDirector()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateDirector(Director director)
        {
            if (ModelState.IsValid)
            {
                if (director.director_id == 0)
                {
                    await directorService.CreateDirector(director);
                }
            }

            return RedirectToAction("Index", "Database");
        }

        [HttpGet]
        public async Task<IActionResult> DeleteDirector()
        {
            var temp_directors = await directorService.GetDirectors();
            if (temp_directors.StatusCode == Enum.StatusCode.OK)
            {
                var directors = temp_directors.Data.ToList();
                if (directors.Count != 0)
                {
                    var Directors = directors.Select(x => new
                    {
                        director_id = x.director_id,
                        req_info = x.director_firstname + " " + x.director_lastname
                    });
                    ViewBag.Directors = new SelectList(Directors, "director_id", "req_info");

                    return View();
                }
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteDirector(Director director)
        {
            var directors = await directorService.DeleteDirector(director);
            if (directors.StatusCode == Enum.StatusCode.OK)
            {
                return RedirectToAction("Index", "Database");
            }

            return RedirectToAction("Index");
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Director/CreateDirector.cshtml
@model Director
@{
    ViewData["Title"] = "Добавление режиссера";
}

<div class="form-container">
    <form method="post" class="form" asp-controller="Director" asp-action="CreateDirector">
        <label class="form-label" asp-for="@Model.director_firstname"></label>
        <input class="form-input" asp-for="@Model.director_firstname" />
        <span class="form-span" asp-validation-for="@Model.director_firstname"></span>

        <label class="form-label" asp-for="@Model.director_lastname"></label>
        <input class="form-input" asp-for="@Model.director_lastname" />
        <span class="form-span" asp-validation-for="@Model.director_lastname"></span>

        <input class="form-button" type="submit" value="Добавить режиссера" />
    </form>
</div>

Views/Director/DeleteDirector.cshtml
@model Director
@{
    ViewData["Title"] = "Удаление режиссера";
}

<div class="form-container">
    <form method="post" class="form" asp-controller="Director" asp-action="DeleteDirector">
        <label class="form-label" asp-for="@Model.director_id"></label>
        <select class="form-select" asp-for=@Model.director_id asp-items="ViewBag.Directors"></select>
        <span class="form-span" asp-validation-for="@Model.director_id"></span>

        <input class="form-button" type="submit" value="Удалить режиссера" />
    </form>
</div>

Views/Director/GetDirectors.cshtml
@model List<Director>

@{

}

@foreach (var director in Model)
{
    <p>@director.director_firstname</p>
}

Views/Director/Index.cshtml
@{

}

<div class="button-main-edit">
    <a href="/Director/CreateDirector" class="button-main">Добавить режиссера</a>
    <a href="/Director/DeleteDirector" class="button-main">Удалить режиссера</a>
</div>